apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-k8s-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-k8s-go
  template:
    metadata:
      labels:
        app: desafio-k8s-go
    spec:
      containers:
      - name: desafio-k8s-go
        image: desafio-k8s-go
        ports:
          - containerPort: 8000