steps:
  - id: go_install
    name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=desafio-k8s-go']
    
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','desafio-k8s-go']
    env: ['PROJECT_ROOT=desafio-k8s-go']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/desafio-k8s-go:latest', '.']

images:
  - 'gcr.io/$PROJECT_ID/desafio-k8s-go:latest'